language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
      rust: 1.31.0

    - env: TARGET=thumbv7m-none-eabi
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
      rust: 1.31.0

    - env: TARGET=x86_64-unknown-linux-gnu
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)
      rust: nightly

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - bash ci/after-success.sh

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
