[package]
name = "lifo"
version = "0.1.0"
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"

[dependencies]
as-slice = "0.1.0"

[dev-dependencies]
generic-array = "0.12.0"

[features]
arch = []
maybe-uninit = []
union = []